name: "onnxruntime"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    dims: [5, 5]
  },
  {
    name: "INITIALIZER"
    data_type: TYPE_FP32
    dims: [5, 5]
    optional: true
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [5, 5]
  }
]
